version: "3"

services:

  rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4000:4000"

    volumes:
      - ./config/default.json:/usr/src/app/config/default.json
